### ISSUE TITLE
Quiz button

### ISSUE THREAD

**Issue by MattWMitchell** [Stream-Line/moodle-mod_streamline#37]
The quiz button is extremely hard to press as the drop down menu keeps disappearing.

**Comment by Akshay224** [comment]
Just to note the actual quiz drop down menu works correctly. The issue is the moodle profile drop down menu located in the top right corner overlays the quiz button. Please see the attached image for further details.

![image](https://cloud.githubusercontent.com/assets/7035118/10312722/1ccb0d24-6c98-11e5-93ad-ca7359a32e7b.png)

**Comment by Akshay224** [comment]
I would also like to note that the moodle drop down menu is displayed differently on all other pages in which the drop down does not overflow from the header. 

It is displayed correctly on the StreamLine session loading page (streamline/view.php) but later seems to overflow once redirected to streamline/streamline_view.php.

**Comment by Akshay224** [comment]
This has been fixed and a pull request submitted with the change.
